spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  main:
    banner-mode: off
  application:
    name: api-kt
  servlet:
    multipart:
      max-file-size: ${HTTP_MAX_BODY_SIZE:10MB}
      max-request-size: ${HTTP_MAX_BODY_SIZE:10MB}
  datasource:
    url: jdbc:${DATABASE_URL:sqlite:app.db}
    driver-class-name: org.sqlite.JDBC
  flyway:
    enabled: ${DATABASE_AUTO_MIGRATE:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379/0}
      timeout: 3
      max-total: 20
      max-idle: 5
  mvc:
    static-path-pattern: ${STATIC_URL:/static}/**
server:
  address: ${HTTP_IP:127.0.0.1}
  port: ${HTTP_PORT:8000}
app:
  search:
    key-prefix: "fts:"
  upload:
    upload-url: ${UPLOAD_URL:uploads}
    upload-dir: ${UPLOAD_PATH:uploads}
    thumbnail-size: ${UPLOAD_THUMB_WIDTH:128}
    image-formats: ${UPLOAD_IMAGE_FORMATS:jpeg,jpg,png,webp,gif}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Content-Type,Authorization}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}
    max-age: ${CORS_MAX_AGE:86400}
  about-url: ${ABOUT_URL:}
pebble:
  expose-request-attributes: true
  suffix:
#management:
#  endpoint:
#    env:
#      enabled: false
#  endpoints:
#    web:
#      exposure:
#        exclude: env

---
spring:
  config:
    activate:
      on-profile: dev
pebble:
  cache: false
logging:
  level:
    root: INFO
    org.jooq: WARN
    site.daydream.pebble: DEBUG
management:
  endpoint:
    env:
      enabled: true
      show-values: always
  endpoints:
    web:
      exposure:
        include: health,info,env

---
spring:
  config:
    activate:
      on-profile: test
app:
  search:
    key-prefix: "fts-test:"
logging:
  level:
    root: warn

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: WARN
