"""initial schema

Revision ID: 98a1ebb8af73
Revises: 
Create Date: 2026-04-30 19:38:55.852186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a1ebb8af73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table('drive_nodes'):
        # Schema already initialised (e.g. by another backend). Record the
        # migration as applied without re-running any DDL.
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('blob_path', sa.Text(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('delete_batch_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("(type = 'folder' AND blob_path IS NULL AND size IS NULL) OR (type = 'file' AND blob_path IS NOT NULL AND size IS NOT NULL)", name='ck_drive_nodes_shape'),
    sa.CheckConstraint("type IN ('folder', 'file')", name='ck_drive_nodes_type'),
    sa.ForeignKeyConstraint(['parent_id'], ['drive_nodes.id'], name=op.f('fk_drive_nodes_parent_id_drive_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drive_nodes'))
    )
    with op.batch_alter_table('drive_nodes', schema=None) as batch_op:
        batch_op.create_index('drive_nodes_delete_batch', ['delete_batch_id'], unique=False)
        batch_op.create_index('drive_nodes_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('drive_nodes_parent', ['parent_id', 'deleted_at'], unique=False)

    # Expression-based indexes that autogenerate cannot reflect under
    # SQLite. Created manually to match models.DriveNode.__table_args__.
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS drive_nodes_unique_active "
        "ON drive_nodes (COALESCE(parent_id, 0), LOWER(name)) "
        "WHERE deleted_at IS NULL"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS drive_nodes_name ON drive_nodes (LOWER(name))"
    )

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], name=op.f('fk_posts_parent_id_posts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sticky', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('drive_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('token_prefix', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['drive_nodes.id'], name=op.f('fk_drive_shares_node_id_drive_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drive_shares')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_drive_shares_token_hash'))
    )
    with op.batch_alter_table('drive_shares', schema=None) as batch_op:
        batch_op.create_index('drive_shares_node', ['node_id'], unique=False)
        batch_op.create_index('drive_shares_prefix', ['token_prefix'], unique=False)

    op.create_table('drive_uploads',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('chunk_size', sa.BigInteger(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('received_mask', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('uploading', 'assembling', 'done', 'failed')", name='ck_drive_uploads_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['drive_nodes.id'], name=op.f('fk_drive_uploads_parent_id_drive_nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drive_uploads'))
    )
    with op.batch_alter_table('drive_uploads', schema=None) as batch_op:
        batch_op.create_index('drive_uploads_expires', ['expires_at'], unique=False)

    op.create_table('tag_post_assoc',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_tag_post_assoc_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tag_post_assoc_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'post_id', name=op.f('pk_tag_post_assoc'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_post_assoc')
    with op.batch_alter_table('drive_uploads', schema=None) as batch_op:
        batch_op.drop_index('drive_uploads_expires')

    op.drop_table('drive_uploads')
    with op.batch_alter_table('drive_shares', schema=None) as batch_op:
        batch_op.drop_index('drive_shares_prefix')
        batch_op.drop_index('drive_shares_node')

    op.drop_table('drive_shares')
    op.drop_table('tags')
    op.drop_table('posts')
    with op.batch_alter_table('drive_nodes', schema=None) as batch_op:
        batch_op.drop_index('drive_nodes_parent')
        batch_op.drop_index('drive_nodes_deleted')
        batch_op.drop_index('drive_nodes_delete_batch')
    op.execute("DROP INDEX IF EXISTS drive_nodes_name")
    op.execute("DROP INDEX IF EXISTS drive_nodes_unique_active")

    op.drop_table('drive_nodes')
    # ### end Alembic commands ###
